import type { Metadata } from "next";
import Navbar from "../components/nav";
import "./globals.css";

export const metadata: Metadata = {
    title: "car-manager",
    description: "Generated by survey your car",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="vsc-initialized">
                <Navbar />
                {children}
            </body>
        </html>
    );
}
